-- ==============================================================================
-- Milestone 4: Admin CMS & Automated Image System Migration
-- Bangladesh Crop Intelligence Assistant
--
-- Instructions: Run this SQL script in your Supabase Dashboard SQL Editor
-- (https://supabase.com/dashboard/project/_/sql)
-- ==============================================================================

-- 1. Create admins table for Role-Based Access Control (RBAC)
CREATE TABLE IF NOT EXISTS public.admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE NOT NULL,
    role TEXT NOT NULL DEFAULT 'admin' CHECK (role IN ('admin', 'editor')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security on admins table
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to view their admin role
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'admins' AND policyname = 'Allow authenticated read admins'
    ) THEN
        CREATE POLICY "Allow authenticated read admins" 
        ON public.admins FOR SELECT 
        TO authenticated 
        USING (true);
    END IF;
END $$;

-- Allow anon read for role verification if needed
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'admins' AND policyname = 'Allow public read admins'
    ) THEN
        CREATE POLICY "Allow public read admins" 
        ON public.admins FOR SELECT 
        TO anon 
        USING (true);
    END IF;
END $$;

-- 2. Add image_url and gallery_urls JSONB to crops table
ALTER TABLE public.crops 
ADD COLUMN IF NOT EXISTS image_url TEXT,
ADD COLUMN IF NOT EXISTS gallery_urls JSONB DEFAULT '[]'::jsonb;

-- 3. Ensure crop_images table exists for relational image tracking
CREATE TABLE IF NOT EXISTS public.crop_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_id BIGINT REFERENCES public.crops(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    caption TEXT,
    is_primary BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create and configure Supabase Storage bucket 'crops'
INSERT INTO storage.buckets (id, name, public) 
VALUES ('crops', 'crops', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Storage Policies for 'crops' bucket
DO $$
BEGIN
    -- Public Read
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname = 'Public Read Crops'
    ) THEN
        CREATE POLICY "Public Read Crops"
        ON storage.objects FOR SELECT
        TO public
        USING (bucket_id = 'crops');
    END IF;

    -- Public / Authenticated Upload
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname = 'Allow Upload to Crops'
    ) THEN
        CREATE POLICY "Allow Upload to Crops"
        ON storage.objects FOR INSERT
        TO public
        WITH CHECK (bucket_id = 'crops');
    END IF;

    -- Public / Authenticated Update
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname = 'Allow Update Crops'
    ) THEN
        CREATE POLICY "Allow Update Crops"
        ON storage.objects FOR UPDATE
        TO public
        USING (bucket_id = 'crops');
    END IF;

    -- Public / Authenticated Delete
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname = 'Allow Delete Crops'
    ) THEN
        CREATE POLICY "Allow Delete Crops"
        ON storage.objects FOR DELETE
        TO public
        USING (bucket_id = 'crops');
    END IF;
END $$;

-- ==============================================================================
-- HELPER: Assign an existing Supabase Auth user as an Admin
-- Replace 'YOUR_ADMIN_EMAIL@example.com' with the email you used to sign up:
--
-- INSERT INTO public.admins (user_id, role)
-- SELECT id, 'admin' FROM auth.users WHERE email = 'YOUR_ADMIN_EMAIL@example.com'
-- ON CONFLICT (user_id) DO NOTHING;
-- ==============================================================================
