"""Synchronize Agricultural Knowledge Base and Rice Varieties into Supabase.

This script:
1. Reads all 31 documents from knowledge_base/metadata/metadata.json
2. Reads all 139 BRRI rice varieties from knowledge_base/reports/brri_rice_varieties_catalog.json
3. Generates backend/data/supabase_knowledge_sync.sql with complete DDL & DML statements
4. Attempts direct sync via Supabase REST API (supports SUPABASE_KEY or SUPABASE_SERVICE_ROLE_KEY)
"""

import json
import os
import re
import sys
from pathlib import Path
from typing import Any, Dict, List

from dotenv import load_dotenv

# Resolve paths
BACKEND_DIR = Path(__file__).resolve().parent.parent
ROOT_DIR = BACKEND_DIR.parent
ENV_PATH = BACKEND_DIR / ".env"
SQL_OUTPUT_PATH = BACKEND_DIR / "data" / "supabase_knowledge_sync.sql"

DOCS_JSON = ROOT_DIR / "knowledge_base" / "metadata" / "metadata.json"
VARIETIES_JSON = ROOT_DIR / "knowledge_base" / "reports" / "brri_rice_varieties_catalog.json"

BN_DIGITS = str.maketrans("0123456789", "০১২৩৪৫৬৭৮৯")


def to_bangla_digits(num_str: str) -> str:
    """Convert ASCII digits to Bengali digits."""
    return str(num_str).translate(BN_DIGITS)


def generate_bangla_variety_name(en_name: str) -> str:
    """Convert English variety name to idiomatic Bangla variety name."""
    s = en_name.strip()
    # Replace prefixes
    if re.match(r"(?i)^brri\s*hybrid\s*dhan\s*(\d+)", s):
        m = re.match(r"(?i)^brri\s*hybrid\s*dhan\s*(\d+)", s)
        return f"ব্রি হাইব্রিড ধান{to_bangla_digits(m.group(1))}"
    elif re.match(r"(?i)^brri\s*dhan\s*(\d+)", s):
        m = re.match(r"(?i)^brri\s*dhan\s*(\d+)", s)
        return f"ব্রি ধান{to_bangla_digits(m.group(1))}"
    elif re.match(r"(?i)^bangabandhu\s*dhan\s*(\d+)", s):
        m = re.match(r"(?i)^bangabandhu\s*dhan\s*(\d+)", s)
        return f"বঙ্গবন্ধু ধান{to_bangla_digits(m.group(1))}"
    elif re.match(r"(?i)^br\s*(\d+)", s):
        m = re.match(r"(?i)^br\s*(\d+)", s)
        return f"বিআর{to_bangla_digits(m.group(1))}"
    return s


def escape_sql(val: Any) -> str:
    """Format value for SQL string literal or NULL."""
    if val is None:
        return "NULL"
    if isinstance(val, bool):
        return "TRUE" if val else "FALSE"
    if isinstance(val, (int, float)):
        return str(val)
    escaped = str(val).replace("'", "''")
    return f"'{escaped}'"


def build_sql_migration(documents: List[Dict[str, Any]], varieties: List[Dict[str, Any]]) -> str:
    """Build complete PostgreSQL migration file with table definitions, RLS, and data inserts."""
    sql = []
    sql.append("-- ==============================================================================")
    sql.append("-- Bangladesh Crop Intelligence Assistant: Knowledge Base & Varieties Migration")
    sql.append(f"-- Total Knowledge Documents: {len(documents)}")
    sql.append(f"-- Total BRRI Rice Varieties: {len(varieties)}")
    sql.append("-- Instructions: Copy and run this script in the Supabase Dashboard SQL Editor")
    sql.append("-- (https://supabase.com/dashboard/project/_/sql)")
    sql.append("-- ==============================================================================\n")

    # 1. Knowledge Documents Table
    sql.append("-- 1. Create knowledge_documents table")
    sql.append("""CREATE TABLE IF NOT EXISTS public.knowledge_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    source TEXT NOT NULL,
    category TEXT NOT NULL,
    language TEXT NOT NULL,
    filename TEXT,
    page_count INTEGER DEFAULT 0,
    char_count INTEGER DEFAULT 0,
    word_count INTEGER DEFAULT 0,
    chunk_count INTEGER DEFAULT 0,
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE public.knowledge_documents ENABLE ROW LEVEL SECURITY;

-- Allow public read access
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'knowledge_documents' AND policyname = 'Allow public read knowledge_documents'
    ) THEN
        CREATE POLICY "Allow public read knowledge_documents" 
        ON public.knowledge_documents FOR SELECT 
        USING (true);
    END IF;
END $$;

-- Allow insert/update for anon & authenticated
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'knowledge_documents' AND policyname = 'Allow write knowledge_documents'
    ) THEN
        CREATE POLICY "Allow write knowledge_documents" 
        ON public.knowledge_documents FOR ALL 
        USING (true)
        WITH CHECK (true);
    END IF;
END $$;
""")

    # 2. Crop Varieties Table
    sql.append("\n-- 2. Create crop_varieties table")
    sql.append("""CREATE TABLE IF NOT EXISTS public.crop_varieties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id TEXT UNIQUE NOT NULL,
    variety_name TEXT NOT NULL,
    variety_name_bn TEXT,
    crop TEXT DEFAULT 'Rice (ধান)',
    category TEXT DEFAULT 'cereals',
    season TEXT,
    source TEXT DEFAULT 'BRRI',
    language TEXT DEFAULT 'Bangla',
    publication_type TEXT,
    original_filename TEXT,
    file_hash TEXT,
    page_count INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE public.crop_varieties ENABLE ROW LEVEL SECURITY;

-- Allow public read access
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'crop_varieties' AND policyname = 'Allow public read crop_varieties'
    ) THEN
        CREATE POLICY "Allow public read crop_varieties" 
        ON public.crop_varieties FOR SELECT 
        USING (true);
    END IF;
END $$;

-- Allow insert/update for anon & authenticated
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'crop_varieties' AND policyname = 'Allow write crop_varieties'
    ) THEN
        CREATE POLICY "Allow write crop_varieties" 
        ON public.crop_varieties FOR ALL 
        USING (true)
        WITH CHECK (true);
    END IF;
END $$;
""")

    # 3. Insert Knowledge Documents
    sql.append("\n-- 3. Upsert Knowledge Documents")
    for doc in documents:
        doc_id = escape_sql(doc.get("document_id"))
        title = escape_sql(doc.get("title"))
        source = escape_sql(doc.get("source"))
        category = escape_sql(doc.get("category"))
        language = escape_sql(doc.get("language"))
        filename = escape_sql(doc.get("filename"))
        page_count = doc.get("page_count", 0)
        char_count = doc.get("char_count", 0)
        word_count = doc.get("word_count", 0)
        chunk_count = doc.get("chunk_count", 0)
        processed_at = escape_sql(doc.get("processed_at"))

        stmt = f"""INSERT INTO public.knowledge_documents (document_id, title, source, category, language, filename, page_count, char_count, word_count, chunk_count, processed_at)
VALUES ({doc_id}, {title}, {source}, {category}, {language}, {filename}, {page_count}, {char_count}, {word_count}, {chunk_count}, {processed_at})
ON CONFLICT (document_id) DO UPDATE SET
    title = EXCLUDED.title,
    source = EXCLUDED.source,
    category = EXCLUDED.category,
    language = EXCLUDED.language,
    filename = EXCLUDED.filename,
    page_count = EXCLUDED.page_count,
    char_count = EXCLUDED.char_count,
    word_count = EXCLUDED.word_count,
    chunk_count = EXCLUDED.chunk_count,
    processed_at = EXCLUDED.processed_at;"""
        sql.append(stmt)

    # 4. Insert Crop Varieties
    sql.append("\n-- 4. Upsert BRRI Rice Varieties")
    for v in varieties:
        doc_id = escape_sql(v.get("document_id"))
        var_name = escape_sql(v.get("variety_name"))
        var_name_bn = escape_sql(v.get("variety_name_bn") or generate_bangla_variety_name(v.get("variety_name", "")))
        crop = escape_sql(v.get("crop", "Rice (ধান)"))
        cat = escape_sql(v.get("category", "cereals"))
        season = escape_sql(v.get("season", "Agriculture Season"))
        src = escape_sql(v.get("source", "BRRI"))
        lang = escape_sql(v.get("language", "Bangla"))
        pub_type = escape_sql(v.get("publication_type", "Rice Variety Fact Sheet / Leaflet"))
        orig_fn = escape_sql(v.get("original_filename", ""))
        f_hash = escape_sql(v.get("file_hash", ""))
        pg_count = v.get("page_count", 1)

        stmt = f"""INSERT INTO public.crop_varieties (document_id, variety_name, variety_name_bn, crop, category, season, source, language, publication_type, original_filename, file_hash, page_count)
VALUES ({doc_id}, {var_name}, {var_name_bn}, {crop}, {cat}, {season}, {src}, {lang}, {pub_type}, {orig_fn}, {f_hash}, {pg_count})
ON CONFLICT (document_id) DO UPDATE SET
    variety_name = EXCLUDED.variety_name,
    variety_name_bn = EXCLUDED.variety_name_bn,
    crop = EXCLUDED.crop,
    category = EXCLUDED.category,
    season = EXCLUDED.season,
    source = EXCLUDED.source,
    language = EXCLUDED.language,
    publication_type = EXCLUDED.publication_type,
    original_filename = EXCLUDED.original_filename,
    file_hash = EXCLUDED.file_hash,
    page_count = EXCLUDED.page_count;"""
        sql.append(stmt)

    sql.append("\n-- Verify counts")
    sql.append("SELECT 'knowledge_documents' AS table_name, count(*) AS total_rows FROM public.knowledge_documents")
    sql.append("UNION ALL")
    sql.append("SELECT 'crop_varieties' AS table_name, count(*) AS total_rows FROM public.crop_varieties;")

    return "\n".join(sql) + "\n"


def sync_via_api(documents: List[Dict[str, Any]], varieties: List[Dict[str, Any]]):
    """Attempt direct sync via Supabase REST API."""
    load_dotenv(dotenv_path=ENV_PATH)
    supabase_url = os.getenv("SUPABASE_URL", "").strip().rstrip("/")
    supabase_key = os.getenv("SUPABASE_SERVICE_ROLE_KEY", "").strip() or os.getenv("SUPABASE_KEY", "").strip()

    if not supabase_url or not supabase_key:
        print("[!] SUPABASE_URL or SUPABASE_KEY missing in backend/.env. Skipping direct API sync.")
        return False

    try:
        from supabase import create_client
        client = create_client(supabase_url, supabase_key)

        print("[*] Checking Supabase tables...")
        # Check documents table
        try:
            client.table("knowledge_documents").select("id").limit(1).execute()
        except Exception as e:
            print(f"[-] Table 'knowledge_documents' not found in schema cache: {e}")
            return False

        # Upsert documents
        print(f"[*] Upserting {len(documents)} knowledge documents via REST API...")
        doc_rows = []
        for d in documents:
            doc_rows.append({
                "document_id": d.get("document_id"),
                "title": d.get("title"),
                "source": d.get("source"),
                "category": d.get("category"),
                "language": d.get("language"),
                "filename": d.get("filename"),
                "page_count": d.get("page_count", 0),
                "char_count": d.get("char_count", 0),
                "word_count": d.get("word_count", 0),
                "chunk_count": d.get("chunk_count", 0),
                "processed_at": d.get("processed_at")
            })
        client.table("knowledge_documents").upsert(doc_rows, on_conflict="document_id").execute()
        print(f"[+] Successfully synced {len(doc_rows)} knowledge documents!")

        # Upsert varieties
        print(f"[*] Upserting {len(varieties)} BRRI varieties via REST API...")
        var_rows = []
        for v in varieties:
            var_rows.append({
                "document_id": v.get("document_id"),
                "variety_name": v.get("variety_name"),
                "variety_name_bn": v.get("variety_name_bn") or generate_bangla_variety_name(v.get("variety_name", "")),
                "crop": v.get("crop", "Rice (ধান)"),
                "category": v.get("category", "cereals"),
                "season": v.get("season", "Agriculture Season"),
                "source": v.get("source", "BRRI"),
                "language": v.get("language", "Bangla"),
                "publication_type": v.get("publication_type", "Rice Variety Fact Sheet / Leaflet"),
                "original_filename": v.get("original_filename", ""),
                "file_hash": v.get("file_hash", ""),
                "page_count": v.get("page_count", 1)
            })
        # Upsert in chunks of 50
        for i in range(0, len(var_rows), 50):
            chunk = var_rows[i:i+50]
            client.table("crop_varieties").upsert(chunk, on_conflict="document_id").execute()
        print(f"[+] Successfully synced {len(var_rows)} BRRI rice varieties!")
        return True

    except Exception as exc:
        print(f"[-] Supabase API sync failed: {exc}")
        return False


def main():
    print("================================================================")
    print("Bangladesh Crop Intelligence Assistant: Supabase Knowledge Sync")
    print("================================================================")

    # 1. Load data
    if not DOCS_JSON.exists():
        print(f"[-] Missing documents JSON: {DOCS_JSON}")
        sys.exit(1)
    if not VARIETIES_JSON.exists():
        print(f"[-] Missing varieties JSON: {VARIETIES_JSON}")
        sys.exit(1)

    with open(DOCS_JSON, "r", encoding="utf-8") as f:
        docs_data = json.load(f).get("documents", [])
    with open(VARIETIES_JSON, "r", encoding="utf-8") as f:
        var_data = json.load(f).get("varieties", [])

    print(f"[+] Loaded {len(docs_data)} knowledge documents.")
    print(f"[+] Loaded {len(var_data)} BRRI rice varieties.")

    # 2. Generate SQL Migration
    print(f"[*] Generating SQL migration file at: {SQL_OUTPUT_PATH}...")
    sql_content = build_sql_migration(docs_data, var_data)
    with open(SQL_OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(sql_content)
    print(f"[+] Generated {SQL_OUTPUT_PATH} ({len(sql_content):,} bytes).")

    # 3. Attempt direct API sync
    print("\n[*] Attempting direct Supabase sync...")
    api_success = sync_via_api(docs_data, var_data)

    if api_success:
        print("\n[SUCCESS] All data has been synchronized directly into Supabase!")
    else:
        print("\n[NOTE] Direct API sync requires tables to exist in Supabase first.")
        print(f"Please execute the generated SQL script in your Supabase Dashboard SQL Editor:")
        print(f"  -> File: {SQL_OUTPUT_PATH}")
        print(f"  -> Supabase URL: https://supabase.com/dashboard/project/_/sql")
        print("This will create both tables ('knowledge_documents', 'crop_varieties'), configure RLS,")
        print("and populate all 170 records in a single step.")


if __name__ == "__main__":
    main()
